### ISSUE TITLE
关于无法起效

### ISSUE THREAD

**Issue by IGNISSU** [Sakura0721/osc-toys#1]
请问Contact reciver处的parameter应该设置为什么？我尝试了EarRDis但是没有效果

**Comment by IGNISSU** [comment]
现在在界面有显示浮点的参数了但是在输出上我却没有感受到任何东西请问这个正常么？以及这个波形改如何切换？

**Comment by IGNISSU** [comment]
这些问题都解决了但是他现在一直会报timeout

**Comment by IGNISSU** [comment]
即便是成功的连接上以后我可以看到float的参数但是却没有感受到有任何的输出，然而在闲置时（刚刚连接上时）却有一定的微弱输出

**Comment by Sakura0721** [comment]
> 请问Contact reciver处的parameter应该设置为什么？我尝试了EarRDis但是没有效果

应该设置成你自己的模型的parameter，详见vrc官方文档。

> 即便是成功的连接上以后我可以看到float的参数但是却没有感受到有任何的输出，然而在闲置时（刚刚连接上时）却有一定的微弱输出

代码里有一个阈值，低于那个阈值的值会被忽略。此外输出强度的更新以秒为单位，因此需要一秒内的平均值高于阈值才行。

https://github.com/Sakura0721/osc-toys/blob/c827ff94eace95c358cdc9ecdffcd0519bf05c45/main.py#LL48C1-L62C13

如果你确认你的操作没问题，请附上没有感受到输出的时间段内的float参数日志。

最近工作有点忙，才看到这个issue。

**Comment by IGNISSU** [comment]
非常感谢你的回复，此外我在使用时还遇到了两个问题，一个是说BLEAK没能搜索到硬件，另一个是找到了硬件正在连接时抱timeout的错误

**Comment by Sakura0721** [comment]
我本地测试偶尔会timeout，多试几次就好了。两次尝试之间间隔不宜太短，郊狼发白光的时候意味着正在配对，你的下一次尝试应该等待郊狼从白光的状态退出之后再进行。

注意，重试需要你Ctrl+C结束程序之后再次运行。

**Comment by Sakura0721** [comment]
另外，为了避免造成意外，默认的`COYOTE_MAX_POWER`的值是较小的。刺激的大小与贴片的部位也有关系。如果你认为刺激太微弱，请慢慢增加该字段的值。

**Comment by IGNISSU** [comment]
哦哦这样非常感谢解答，我这边看默认值是100，请问这是对应郊狼的100么？

**Comment by IGNISSU** [comment]
以及郊狼持续白光是是正在配对然后白光闪烁就是连接上了对么？

**Comment by ACYXXXX** [comment]
我连接上了我的郊狼，但是vrchat里的OSC DEBUG却没有显示任何东西，是空白的

**Comment by Sakura0721** [comment]
确实存在稳定性问题，但是暂时不确定是郊狼的问题还是蓝牙库的问题。但是存在其他用户能够正常运行。

先关闭此issue，后续再有问题再打开。

**Comment by Sakura0721** [comment]
在 #3 中增加了蓝牙连接的超时时间，timeout的现象应该有所好转。
